Added basic version handling to kpm

diff --git a/iso/install/setup b/iso/install/setup
--- a/iso/install/setup
+++ b/iso/install/setup
@@ -1,13 +1,7 @@
 #!/bin/sh
 
-KPMVER="1.0"
-GRUBVER="2.12"
-UTILVER="2.40"
-E2FSVER="1.47.0"
-BASEVER="1.0"
-
 #Install the packaged kpm first using the kpm which was on the ISO (may be a simplified version later)
-sh /mnt/iso/install/kpm install kpm-$KPMVER || { echo "kpm error, installation cancelled!"; break; }
+sh /mnt/iso/install/kpm install kpm || { echo "kpm error, installation cancelled!"; exit 1; }
 
 KARLS=`cat /mnt/iso/karls_iso`
 echo ""
@@ -54,7 +48,7 @@ echo "Partitioning disk for MBR..."
 echo -e "o\nn\np\n1\n2048\n\na\n1\nw\n" | fdisk $TRGT > /dev/null || { echo "fdisk error, installation cancelled!"; break; }
 
 echo "Formatting Linux partition..."
-kpm install e2fsprogs-$E2FSVER || { echo "kpm error, installation cancelled!"; break; }
+kpm install e2fsprogs || { echo "kpm error, installation cancelled!"; break; }
 mkfs.ext4 "$TRGT"1 > /dev/null || { echo "mkfs.ext4 error, installation cancelled!"; break; }
 
 echo "Mounting target..."
@@ -62,12 +56,12 @@ mkdir -p /mnt/target
 mount "$TRGT"1 /mnt/target > /dev/null || { echo "mount error, installation cancelled!"; break; }
 
 else
-kpm install util_linux-$UTILVER || { echo "kpm error, installation cancelled!"; break; }
+kpm install util_linux || { echo "kpm error, installation cancelled!"; break; }
 echo "Partitioning disk for GPT..."
 echo -e "g\nn\n1\n2048\n+64M\nt\n1\nn\n2\n\n\nw\n" | /usr/sbin/fdisk -W always $TRGT > /dev/null || { echo "fdisk error, installation cancelled!"; break; }
 
 echo "Formatting partitions..."
-kpm install e2fsprogs-$E2FSVER || { echo "kpm error, installation cancelled!"; break; }
+kpm install e2fsprogs || { echo "kpm error, installation cancelled!"; break; }
 mkfs.vfat "$TRGT"1 > /dev/null || { echo "mkfs.vfat error, installation cancelled!"; break; }
 mkfs.ext4 "$TRGT"2 > /dev/null || { echo "mkfs.ext4 error, installation cancelled!"; break; }
 
@@ -82,7 +76,7 @@ echo "Installing Kernel files..."
 KVER=`cat /mnt/iso/boot/kernel_version`
 mkdir -p /mnt/target/boot/grub /mnt/target/etc/kpm
 cp /etc/kpm/repo /mnt/target/etc/kpm
-kpm install kernel-$KVER /mnt/target || { echo "kpm error, installation cancelled!"; break; }
+kpm install kernel /mnt/target || { echo "kpm error, installation cancelled!"; break; }
 
 echo "Installing GRUB boot loader..."
 
@@ -129,11 +123,11 @@ echo "	initrd /boot/initrd-$KVER.gz" >> /mnt/target/boot/grub/grub.cfg
 echo "}" >> /mnt/target/boot/grub/grub.cfg
 
 if [ "$UEFI" == "0" ]; then
-kpm install grub-$GRUBVER || { echo "kpm error, installation cancelled!"; break; }
+kpm install grub || { echo "kpm error, installation cancelled!"; break; }
 grub-install --boot-directory=/mnt/target/boot "$TRGT" || { echo "grub-install error, installation cancelled!"; break; }
 
 else
-kpm install grub-$GRUBVER-efi || { echo "kpm error, installation cancelled!"; break; }
+kpm install grub_efi || { echo "kpm error, installation cancelled!"; break; }
 mkdir -p /mnt/target/boot/efi/EFI/BOOT
 
 echo "search -u $BLK --set=root" > /mnt/target/boot/grub/grub-early.cfg
@@ -148,7 +142,7 @@ fi
 
 echo "Installing base OS packages..."
 
-kpm install karls_base-$BASEVER /mnt/target || { echo "kpm error, installation cancelled!"; break; }
+kpm install karls_base /mnt/target || { echo "kpm error, installation cancelled!"; break; }
 
 if [ -z "$SERIALCON" ]; then
  rm /mnt/target/etc/inittab-serial
@@ -157,9 +151,9 @@ else
 fi
 
 if [ "$UEFI" == "0" ]; then
-kpm install grub-$GRUBVER /mnt/target || { echo "kpm error, installation cancelled!"; break; }
+kpm install grub /mnt/target || { echo "kpm error, installation cancelled!"; break; }
 else
-kpm install grub-$GRUBVER-efi /mnt/target || { echo "kpm error, installation cancelled!"; break; }
+kpm install grub_efi /mnt/target || { echo "kpm error, installation cancelled!"; break; }
 echo "$TRGT""1		/boot/efi	vfat	ro,defaults,nosuid,nodev,noexec 0 0" >> /mnt/target/etc/fstab
 fi
 
@@ -179,7 +173,7 @@ break
 done
 
 echo ""
-echo "Press Any Key to Reboot or \"S\" to drop to Live ISO Shell"
+echo "Press Any Key to Reboot or \"S\" to drop to Live ISO Shell (E.g. to install further packages with kpm to /mnt/target)"
 read -s -n 1
 REP=`echo $REPLY | tr '[:upper:]' '[:lower:]'`
 [[ "$REP" == "s" ]] && exit 0
