Initrd now properly switch_root if root= kernel parameter found

diff --git a/iso/install/setup b/iso/install/setup
--- a/iso/install/setup
+++ b/iso/install/setup
@@ -39,44 +39,37 @@ read
 
 echo "Partitioning disk..."
 echo -e "o\nn\np\n1\n2048\n\na\n1\nw\n" | fdisk $TRGT > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "fdisk error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "fdisk error, installation cancelled!"; break; }
 
 echo "Formatting ext2 partition..."
 mkfs.ext2 "$TRGT"1 > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "mkfs.ext2 error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "mkfs.ext2 error, installation cancelled!"; break; }
 
 echo "Mounting target..."
 mkdir -p /mnt/target
 mount "$TRGT"1 /mnt/target > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "mount error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "mount error, installation cancelled!"; break; }
 
 echo "Unpacking installation dependencies to ramdisk..."
 for pkg in `cat /mnt/iso/install/instdep.list`; do
 kpm install /mnt/iso/packages/$pkg > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
 done
 
 echo "Installing Kernel files..."
 KVER=`cat /mnt/iso/boot/kernel_version`
 mkdir -p /mnt/target/boot/grub
 kpm install /mnt/iso/packages/kernel-$KVER.kp /mnt/target > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
 
 echo "Installing GRUB boot loader..."
 GRUBVER=`cat /mnt/iso/install/grub_ver`
 
 kpm install /mnt/iso/packages/grub-$GRUBVER.kp > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
 
 grub-install --boot-directory=/mnt/target/boot "$TRGT"
-ret=$?
-[[ $ret -ne 0 ]] && { echo "grub-install error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "grub-install error, installation cancelled!"; break; }
 
 cp /mnt/iso/install/grub.cfg /mnt/target/boot/grub
 
@@ -98,13 +91,11 @@ echo "Installing base OS packages..."
 
 for pkg in `cat /mnt/iso/install/base.list`; do
 kpm install /mnt/iso/packages/$pkg /mnt/target > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
 done
 
 kpm install /mnt/iso/packages/grub-$GRUBVER.kp /mnt/target > /dev/null
-ret=$?
-[[ $ret -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
+[[ $? -ne 0 ]] && { echo "kpm error, installation cancelled!"; break; }
 
 echo ""
 echo "KarLS Installation finished!"
diff --git a/kernel/skel/init b/kernel/skel/init
--- a/kernel/skel/init
+++ b/kernel/skel/init
@@ -6,9 +6,7 @@ mount -t devtmpfs /dev /dev
 #Mount fstab - /proc /sys /tmp
 mount -a
 
-mkdir -p /dev/pts /tmp/var/run /tmp/var/log /tmp/var/lock
-
-mount -t devpts /dev/pts /dev/pts
+mkdir -p /tmp/var/run /tmp/var/log /tmp/var/lock
 
 #Run 3 times, because new devices found after initial module load
 /etc/init.d/rcS-detect_kmods 2> /dev/null
@@ -22,10 +20,21 @@ ROOTUUID=`cat /proc/cmdline | tr ' ' '\n' | grep root= | cut -d= -f2`
 [[ ! -z "$ROOTUUID" ]] && ROOTDISK=`blkid | grep $ROOTUUID | cut -d: -f1`
 
 if [ -b "$ROOTDISK" ]; then
+ #Ugly, ugly, ugly. It will never loop ofc, but I can abort commands before switch_rooe this way
+ while true; do
  mkdir /newroot
- mount -o ro $ROOTDISK /newroot
- ret=$?
- [[ $ret -ne 0 ]] && echo "Could not mount root FS!"
+ mount $ROOTDISK /newroot
+ [[ $? -ne 0 ]] && { echo "Could not mount root FS!"; break; }
+ mount --move /sys /newroot/sys
+ [[ $? -ne 0 ]] && { echo "Could not move mount point for /sys!"; break; }
+ mount --move /dev /newroot/dev
+ [[ $? -ne 0 ]] && { echo "Could not move mount point for /dev!"; break; }
+ mount --move /proc /newroot/proc
+ [[ $? -ne 0 ]] && { echo "Could not move mount point for /proc!"; break; }
+ exec switch_root /newroot /bin/init
+ break
+ done
 fi
 
+#Fall back to Initrd Init if no root found - this will launch setup for example if ISO parameter found
 exec /bin/init <dev/console >dev/console 2>&1
diff --git a/pkg/pkg/kpm b/pkg/pkg/kpm
--- a/pkg/pkg/kpm
+++ b/pkg/pkg/kpm
@@ -24,8 +24,7 @@ KPF=$2
 
 echo "Unpacking $KPF to $DST..."
 tar -C $DST -xJf $KPF
-ret=$?
-[[ $ret -ne 0 ]] && { echo "Package error with $KPF, installation cancelled!" 1>&2; exit 1; }
+[[ $? -ne 0 ]] && { echo "Package error with $KPF, installation cancelled!" 1>&2; exit 1; }
 
 if [ -f "$DST/INSTALL" ]; then
  echo "Running install script..."
